### ISSUE TITLE
Component details are incomplete on the schematic file

### ISSUE THREAD

**Issue by mohanbabubb** [bitcraze/hardware#10]
https://github.com/bitcraze/hardware/raw/master/src/products/crazyradio-pa/electronics/crazyradio-pa_rev.b.pdf , most of the schematic resistors, capacitors doesn't have a proper type and part identification for recognizing/transparent about the use of ROHS based or cheap resistors.

**Comment by tobbeanton** [comment]
I'm not sure what you are really requesting? For generic parts we normally don't specify the exact part number. This information is in the BOM which we don't share because there was no "giving back", only clones. Even in the BOM some components can be pretty generic but there we have requirements such as RoHS and other things.

I'm closing this since this is something we intend not to change.
